# Generated by Django 5.2.1 on 2025-06-01 20:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='replyvote',
            unique_together={('user', 'reply')},
        ),
        migrations.AlterUniqueTogether(
            name='topicvote',
            unique_together={('user', 'topic')},
        ),
        migrations.RemoveField(
            model_name='replyvote',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='replyvote',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='topicvote',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='topicvote',
            name='object_id',
        ),
    ]
